# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='loanId',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='singleOrGroup',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
