# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbank', '0002_auto_20170608_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
