# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbank', '0002_auto_20170609_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deposit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
