# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microbank', '0003_client_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loanPayed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
